# Generated by Django 3.2.8 on 2021-10-14 20:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211014_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
